### ISSUE TITLE
Montar scripts que serão rodados nas aulas

### ISSUE THREAD

**Issue by jtrecenti** [curso-r/curso-r.github.com#12]
Eu comecei a construir os scripts em R das aulas que serão dadas (abrindo o RStudio na frente de todos). Ainda estou pensando em como é a melhor forma de deixar isso disponível publicamente. 

Pensei em duas opções

- Adicionar uma aba à página do curso com os scripts
- Adicionar em cada aula um link para baixar o script que foi rodado

O que acham?

**Comment by williamorim** [comment]
Acho que as duas opções são ok, mas prefiro a segunda.

Em 12 de janeiro de 2015 08:11, Julio Trecenti <notifications@github.com>
escreveu:

> Eu comecei a construir os scripts em R das aulas que serão dadas (abrindo
> o RStudio na frente de todos). Ainda estou pensando em como é a melhor
> forma de deixar isso disponível publicamente.
>
> Pensei em duas opções
>
>    - Adicionar uma aba à página do curso com os scripts
>    - Adicionar em cada aula um link para baixar o script que foi rodado
>
> O que acham?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/curso-r/curso-r.github.com/issues/12>.
>



-- 
William Nilson de Amorim
Mestrando em Estatística pelo Instituto de Matemática e
Estatística da Universidade de São Paulo - IMEUSP

**Comment by Athospd** [comment]
Voto na 2 tbm!
