### ISSUE TITLE
About do curso

### ISSUE THREAD

**Issue by dfalbel** [curso-r/curso-r.github.com#7]
Vamos escrever um about do curso?

Acho que aqui podemos colocar os pré-requisitos do curso que nem o Athos sugeriu!

**Comment by jtrecenti** [comment]
foram adicionados os links e esta tudo ok.

OBS para adicionar referencias num rmd, da pra add um .bib por aqui: http://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html
